export const ROUTE_PATHS = {
  root: '',
  auth: 'auth',
  signIn: '/auth/sign-in',
  dashboard: '/dashboard',
  projects: '/projects',
  curriculum: '/projects/curriculum',
  tasks: '/tasks',
  taskBoard: (projectId: number | string) => `/tasks/${projectId}/board`,
  taskSheet: (projectId: number | string) => `/tasks/${projectId}/sheet`,
  sprints: '/sprints',
  sprintBoard: (sprintId: number | string) => `/sprints/${sprintId}/board`,
  myLeaves: '/leaves/mine',
  leaveCalendar: '/leaves/calendar',
  membersLeaves: '/leaves/members',
  memberLeaveHistory: (userId: number | string) => `/leaves/members/${userId}`,
  users: '/resources/users',
  roles: '/resources/roles',
  teams: '/resources/teams',
  sections: '/resources/sections',
  schemas: '/workflows/schemas',
  taskBank: '/workflows/task-bank',
  notFound: '/errors/404',
} as const;
