import { environment } from '@environments/environment';

export const API = {
  baseUrl: environment.baseURL,
  Auth: {
    Login: '/auth/login',
    AboutMe: '/auth/about-me',
    Logout: '/auth/logout',
    Refresh: '/auth/refresh-token',
  },
  Users: {
    List: '/identity/users',
    ById: '/identity/users/{id}',
    Create: '/identity/users',
    Update: '/identity/users/{id}',
    Archive: '/identity/users/{id}',
    AssignRole: '/identity/users/{id}/role',
    TeamLeaders: '/identity/users/team-leaders',
  },
  Roles: {
    List: '/identity/roles',
    Create: '/identity/roles',
    ById: '/identity/roles/{id}',
    Update: '/identity/roles/{id}',
    Archive: '/identity/roles/{id}',
    Permissions: '/identity/roles/{id}/permissions',
  },
  RbacPermissions: {
    List: '/identity/permissions',
  },
  Teams: {
    List: '/organization/teams',
    Create: '/organization/teams',
    ById: '/organization/teams/{id}',
    Update: '/organization/teams/{id}',
    Archive: '/organization/teams/{id}',
  },
  Sections: {
    List: '/organization/sections',
    Create: '/organization/sections',
    ById: '/organization/sections/{id}',
    Update: '/organization/sections/{id}',
    Archive: '/organization/sections/{id}',
  },
  Curriculum: {
    Years: '/curriculum/years',
    YearById: '/curriculum/years/{id}',
    YearTree: '/curriculum/years/{id}/tree',
    YearProjects: '/curriculum/years/{yearId}/projects',
    ProjectById: '/curriculum/projects/{id}',
    ProjectTerms: '/curriculum/projects/{projectId}/terms',
    TermById: '/curriculum/terms/{id}',
    TermGroups: '/curriculum/terms/{termId}/subject-groups',
    GroupById: '/curriculum/subject-groups/{id}',
    GroupSubjects: '/curriculum/subject-groups/{subjectGroupId}/subjects',
    SubjectsCatalog: '/curriculum/subjects',
    SubjectFilterOptions: '/curriculum/subjects/filter-options',
    SubjectsExport: '/curriculum/subjects/export',
    Subject: '/curriculum/subjects/{id}',
    SubjectStatus: '/curriculum/subjects/{id}/status',
    SubjectUsers: '/curriculum/subjects/{id}/users',
    SubjectUnassign: '/curriculum/subjects/{id}/users/unassign',
    SubjectUnits: '/curriculum/subjects/{subjectId}/units',
    UnitById: '/curriculum/units/{id}',
    UnitLessons: '/curriculum/units/{unitId}/lessons',
    LessonById: '/curriculum/lessons/{id}',
    LessonLos: '/curriculum/lessons/{lessonId}/learning-objectives',
    LearningObjective: '/curriculum/learning-objectives/{id}',
  },
  Schemas: {
    List: '/workflows/schemas',
    Create: '/workflows/schemas',
    ById: '/workflows/schemas/{id}',
    Update: '/workflows/schemas/{id}',
    Archive: '/workflows/schemas/{id}',
    Nodes: '/workflows/schemas/{schemaId}/nodes',
  },
  SchemaTypes: {
    List: '/workflows/schema-types',
  },
  WorkflowNodes: {
    ById: '/workflows/nodes/{id}',
    Steps: '/workflows/nodes/{nodeId}/steps',
  },
  WorkflowSteps: {
    ById: '/workflows/steps/{id}',
  },
  Tickets: {
    ListBySubject: '/subjects/{id}/tickets',
    ListBySprint: '/sprints/{id}/tickets',
    ListByLo: '/learning-objectives/{id}/tickets',
    Stats: '/tickets/stats',
    ById: '/tickets/{id}',
    Create: '/tickets',
    Proceed: '/tickets/{id}/proceed',
    Complete: '/tickets/{id}/complete',
    Assign: '/tickets/{id}/assign',
    Flag: '/tickets/{id}/flag',
    Rollback: '/tickets/{id}/rollback',
    Skip: '/tickets/{id}/skip',
    JumpPoints: '/tickets/{id}/jump-points',
    Jump: '/tickets/{id}/jump',
    Priority: '/tickets/{id}/priority',
    Pause: '/tickets/{id}/pause',
    Activity: '/tickets/{id}/activity',
    Comments: '/tickets/{id}/comments',
    CommentById: '/tickets/{id}/comments/{commentId}',
    WorkTimeStart: '/tickets/{id}/work-times/start',
    WorkTimeStop: '/tickets/{id}/work-times/stop',
  },
  TaskBank: {
    List: '/workflows/ticket-bank',
    Create: '/workflows/ticket-bank',
    ById: '/workflows/ticket-bank/{id}',
    Update: '/workflows/ticket-bank/{id}',
    Archive: '/workflows/ticket-bank/{id}',
  },
  Sprints: {
    List: '/sprints',
    Create: '/sprints',
    ById: '/sprints/{id}',
    Update: '/sprints/{id}',
    Archive: '/sprints/{id}',
    LearningObjectives: '/sprints/{id}/learning-objectives',
    RemoveLearningObjective: '/sprints/{id}/learning-objectives/{loId}',
  },
  Leaves: {
    Balances: '/hr/leave/balances',
    BalancesByUser: '/hr/leave/balances/{userId}',
    Settings: '/hr/leave/leave-settings',
    Preview: '/hr/leave/leave-requests/preview',
    List: '/hr/leave/leave-requests',
    Search: '/hr/leave/leave-requests/search',
    Pending: '/hr/leave/leave-requests/pending',
    ById: '/hr/leave/leave-requests/{id}',
    Cancel: '/hr/leave/leave-requests/{id}/cancel',
    Opinion: '/hr/leave/leave-requests/{id}/opinions',
    BulkOpinion: '/hr/leave/leave-requests/opinions/bulk',
    Approve: '/hr/leave/leave-requests/{id}/approve',
    MedicalCertificate: '/hr/leave/leave-requests/{id}/medical-certificate',
  },
  Permissions: {
    List: '/hr/permissions',
    Search: '/hr/permissions/search',
    Pending: '/hr/permissions/pending',
    ById: '/hr/permissions/{id}',
    Cancel: '/hr/permissions/{id}/cancel',
    Opinion: '/hr/permissions/{id}/opinions',
    BulkOpinion: '/hr/permissions/opinions/bulk',
    Approve: '/hr/permissions/{id}/approve',
  },
  WorkFromHome: {
    List: '/hr/work-from-home',
    Search: '/hr/work-from-home/search',
    Pending: '/hr/work-from-home/pending',
    ById: '/hr/work-from-home/{id}',
    Cancel: '/hr/work-from-home/{id}/cancel',
    Opinion: '/hr/work-from-home/{id}/opinions',
    BulkOpinion: '/hr/work-from-home/opinions/bulk',
    Approve: '/hr/work-from-home/{id}/approve',
  },
  ForgotClock: {
    List: '/hr/forgot-clock',
    Search: '/hr/forgot-clock/search',
    Pending: '/hr/forgot-clock/pending',
    ById: '/hr/forgot-clock/{id}',
    Cancel: '/hr/forgot-clock/{id}/cancel',
    Opinion: '/hr/forgot-clock/{id}/opinions',
    BulkOpinion: '/hr/forgot-clock/opinions/bulk',
    Approve: '/hr/forgot-clock/{id}/approve',
  },
  Holidays: {
    List: '/hr/holidays',
    Create: '/hr/holidays',
    Update: '/hr/holidays/{id}',
    Delete: '/hr/holidays/{id}',
  },
  Notifications: {
    List: '/notifications',
    ById: '/notifications/{id}',
    Read: '/notifications/{id}/read',
    ReadAll: '/notifications/read-all',
  },
} as const;

export function apiPath(template: string, params: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => encodeURIComponent(String(params[key])));
}
